repos:
   - repo: https://github.com/pre-commit/pre-commit-hooks
     rev: v4.0.1
     hooks:
        - id: trailing-whitespace
        - id: check-added-large-files
        - id: check-merge-conflict
        - id: check-symlinks
        - id: destroyed-symlinks
        - id: detect-private-key
        - id: mixed-line-ending
        - id: end-of-file-fixer
   - repo: https://github.com/adrienverge/yamllint
     rev: v1.33.0
     hooks:
        - id: yamllint
   - repo: https://github.com/igorshubovych/markdownlint-cli
     rev: v0.38.0
     hooks:
        - id: markdownlint-docker
        - id: markdownlint-fix-docker

   - repo: https://github.com/antonbabenko/pre-commit-terraform
     rev: v1.85.0
     hooks:
        - id: terraform_fmt
        - id: terraform_tflint
          args:
             - --args=--config=__GIT_WORKING_DIR__/.tflint.hcl
        - id: terraform_trivy
